config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs, controllers: {
  		sessions: 'chefs/sessions',
        registrations: 'chefs/registrations'
      }
  devise_for :users, controllers: {
  		sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
      get '/chefs/:id/show' => "chefs#show", as: "chefs_show"
      get '/users/index' => "users#index"
      resources :chef_reviews
   resources :requests
	 root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chef_reviews

  has_attached_file :avatar, :styles => 
  { :medium => "300x300>", :thumb => "100x100>"}, 
  :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, 
  :content_type => /\Aimage\/.*\Z/
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
	belongs_to :chef
	belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_review.rb
class UserReview < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception

  	def after_sign_in_path_for(user)
  		users_index_path
	end
end

app/controllers/chef_reviews_controller.rb
class ChefReviewsController < ApplicationController
  def index
  end

  def new
    @review = ChefReview.new
  end

  def edit
  end

  def create
    @chef = Chef.find(params[:chef_id])
    @review = @chef.chef_reviews.new(review_params)
    respond_to do |format|
      if @review.save
        format.js
      end
    end
  end

  def show
  end

  def update
  end

  def destroy
  end

  private 
  def review_params
    params.require(:chef_review).permit(:chef_id, :user_id, :description)
  end
end

app/controllers/chefs/confirmations_controller.rb
class Chefs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/chefs/omniauth_callbacks_controller.rb
class Chefs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/chefs/passwords_controller.rb
class Chefs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/chefs/registrations_controller.rb
class Chefs::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :specialty, :description, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname, :lname, :specialty, :description, :avatar])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/chefs/sessions_controller.rb
class Chefs::SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/chefs/unlocks_controller.rb
class Chefs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
  end

  def show
  	@user = current_user
    @chef = Chef.find(params[:id])
  	@review = ChefReview.new
  end
  def new
  	@review = ChefReview.new
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.new
  	@chef = Chef.new
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def update
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@chefs = Chef.all
  	@user = current_user
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_reviews_helper.rb
module ChefReviewsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chefs/index.html.erb
<h1>Chefs#index</h1>
<p>Find me in app/views/chefs/index.html.erb</p>

app/views/chefs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", root_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/chefs/show.html.erb
<div id="chefwrap">
	<div class="row" id="rows">
	  <div class="col-md-3" id="profilepic">
	  	<div id="parentpropic">
			<%= image_tag @chef.avatar.url, :id => "propic"%> 
		</div>
	  </div>
	  <div class="col-md-6" id="profileinfo">
	  	<h1 id="cname">Chef: <%= @chef.fname %> <%= @chef.lname %></h1>
	  	<h3 id="cspec">Specialty: <%= @chef.specialty %></h3>
	  	<h3 id="cdes">description: </h3>
	  	<%= @chef.description %>
	  </div>
	</div>
	<br>
	<% if current_user %>
		<div class="modal reqmodal fade" id="myModalHorizontal" tabindex="-1" role="dialog" 
		     aria-labelledby="myModalLabel" aria-hidden="true">
		    <div class="modal-dialog">
		        <div class="modal-content">
		            <!-- Modal Header -->
		            <div class="modal-header">
		                <button type="button" class="close" 
		                   data-dismiss="modal">
		                       <span aria-hidden="true">&times;</span>
		                       <span class="sr-only">Close</span>
		                </button>
		                <h4 class="modal-title" id="myModalLabel">
		                    Chef Request
		                </h4>
		            </div>
		            
		            <!-- Modal Body -->
		            <div class="modal-body">
		                
		                <form class="form-horizontal" role="form">
		                  <div class="form-group">
		                    <label  class="col-sm-2 control-label"
		                              for="inputEmail3">Email</label>
		                    <div class="col-sm-10">
		                        <input type="email" class="form-control" 
		                        id="inputEmail3" placeholder="Email"/>
		                    </div>
		                  </div>
		                  <div class="form-group">
		                    <label class="col-sm-2 control-label"
		                          for="guests" >Guests</label>
		                    <div class="col-sm-10">
		                        <input type="" class="form-control"
		                            id="guests" placeholder="How many guests"/>
		                    </div>
		                  </div>
		                  <div class="form-group">
		                    <label class="col-sm-2 control-label"
		                          for="foodtype" >Food</label>
		                    <div class="col-sm-10">
		                        <input type="" class="form-control"
		                            id="foodtype" placeholder="What would you like to eat?"/>
		                    </div>
		                  </div>
		                  <div class="form-group">
		                    <label class="col-sm-2 control-label"
		                          for="date" >Date</label>
		                    <div class="col-sm-10">
		                        <input type="Date" class="form-control"
		                            id="date" placeholder=""/>
		                    </div>
		                  </div>	                  
		                </form>     
		            </div>
		            <!-- Modal Footer -->
		            <div class="modal-footer">
		                <button type="button" class="btn btn-default"
		                        data-dismiss="modal">
		                            Close
		                </button>
		                <button type="button" class="btn btn-primary">
		                    Send request
		                </button>
		            </div>
		        </div>
		    </div>
		</div>
		<br>
		<br>
			<div class="modal revmodal fade" id="myModalHorizontal revmod" tabindex="-1" role="dialog" 
		     aria-labelledby="myModalLabel" aria-hidden="true">
		    <div class="modal-dialog">
		        <div class="modal-content">
		            <!-- Modal Header -->
		            <div class="modal-header">
		                <button type="button" class="close" 
		                   data-dismiss="modal">
		                       <span aria-hidden="true">&times;</span>
		                       <span class="sr-only">Close</span>
		                </button>
		                <h4 class="modal-title" id="myModalLabel">
		                    Chef Review
		                </h4>
		            </div>
		            
		            <!-- Modal Body -->
		            <div class="modal-body">
						<%= form_for @review, remote: true do |f| %>
							<%= hidden_field_tag :chef_id, @chef.id %>
							<%= f.hidden_field :user_id, value: @user.id %>
							<%= f.label :description, "Write A Review!" %>
							<%= f.text_area :description %>
							<%= f.submit %>
						<% end %>
		            </div>
		            <!-- Modal Footer -->
		            <div class="modal-footer">
		                <button type="button" class="btn btn-default"
		                        data-dismiss="modal">
		                            Close
		                </button>
		                <button type="button" class="btn btn-primary">
		                    Send Review
		                </button>
		            </div>
		        </div>
		    </div>
		</div>
		<br>
		<div id="butdiv">
			<div id=butndiv>
				<button id="request">Make A Request</button>
			</div>
			<div id=butndiv>
				<button id="newreview">Leave a Review</button>
			</div>
		</div>
		<% end %>
	<br>
	<div class="row" id="rows">
	  <div class="col-md-10" id="reviews">
		<% @chef.chef_reviews.each do |chef_review|%>
			<%= render "chef_reviews/chef_review", chef_review: chef_review %>
		<% end %>
	  </div>
	</div>
</div>