config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs, controllers: {
  		sessions: 'chefs/sessions',
        registrations: 'chefs/registrations'
      }
  devise_for :users, controllers: {
  		sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
      get '/chefs/:id/show' => "chefs#show", as: "chefs_show"
      get '/users/index' => "users#index"
      resources :chef_reviews
   resources :requests
	 root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chef_reviews

  has_attached_file :avatar, :styles => 
  { :medium => "300x300>", :thumb => "100x100>"}, 
  :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, 
  :content_type => /\Aimage\/.*\Z/
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
	belongs_to :chef
	belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_review.rb
class UserReview < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception

  	def after_sign_in_path_for(user)
  		users_index_path
	end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
  end

  def show
  	@user = current_user
    @chef = Chef.find(params[:id])
  	@review = ChefReview.new
  end
  def new
  	@review = ChefReview.new
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.new
  	@chef = Chef.new
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def update
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@chefs = Chef.all
  	@user = current_user
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_reviews_helper.rb
module ChefReviewsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="welcome">
	<h1 id="welcomeword">Welcome to Chef-O!</h1>
</div>
<br>
<br>
<div class="chefwrap">
	<div class="col-md-offset-1 col-md-4 cheflog ">
		<h2>Are you a Chef?</h2>
		<%= form_for( @chef, url: new_chef_session_path) do |f| %>
		    <div class="field">	    	
		    	<%= f.email_field :email, placeholder: "Email", autofocus: true, :class => "btn btn-default", :id => "chefmail" %>
		    </div>
			<br />
		    <div class="field">
		    	<%= f.password_field :password, placeholder: "Password", autocomplete: "off", :class => "btn btn-default" %><br />
		    </div>
			<br />
		    <div class="actions">
		    	<%= f.submit "Log in", :class => "btn btn-default" %>
		    </div>
		<% end %>
		<h3><%= link_to "Create Account".html_safe, new_chef_registration_path, :id => "button_id", :class => "btn btn-default" %></h3> 
	</div>
</div>
<div class="userwrap">
	<div class="col-md-offset-2 col-md-4 userlog ">
	  	<h2 id="test" >Are you looking for a Chef?</h2>
	  	<%= form_for(@user, url: user_session_path ) do |f| %>
		    <div class="field" >
		    	
		    	<%= f.email_field :email, placeholder: "Email", :class => "btn btn-default" %> <br />
		    </div>
			<br />
		    <div class="field">
		    	
		    	<%= f.password_field :password, placeholder: "Password", :class => "btn btn-default" %> <br />
		    </div>
			<br />
		    <div class="actions">
		    	<%= f.submit "Log in", :class => "btn btn-default" %>
		    </div>
		<% end %>
		<h3><%= link_to "Create Account".html_safe, new_user_registration_path, :id => "button_id", :class => "btn btn-default" %></h3>
	</div>
</div>