config/routes.rb
Rails.application.routes.draw do
  devise_for :chefs, controllers: {
  		sessions: 'chefs/sessions',
        registrations: 'chefs/registrations'
      }
  devise_for :users, controllers: {
  		sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
      get '/chefs/:id/show' => "chefs#show", as: "chefs_show"
      get '/users/index' => "users#index"
      resources :chef_reviews
   resources :requests
	 root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chef_reviews

  has_attached_file :avatar, :styles => 
  { :medium => "300x300>", :thumb => "100x100>"}, 
  :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, 
  :content_type => /\Aimage\/.*\Z/
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
	belongs_to :chef
	belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_review.rb
class UserReview < ApplicationRecord
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
  end

  def show
  	@user = current_user
    @chef = Chef.find(params[:id])
  	@review = ChefReview.new
  end
  def new
  	@review = ChefReview.new
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.new
  	@chef = Chef.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@chefs = Chef.all
  	@user = current_user
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_reviews_helper.rb
module ChefReviewsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finalgroup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if current_user %>
	  	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Mr.Chef-O", users_index_path, :id => "chefo" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "Chefs", users_index_path,:id => "account" %></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="chefo">Account<span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to "Settings", edit_user_registration_path %></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<% elsif current_chef %>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Mr.Chef-O", users_index_path, :id => "chefo" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="account">Account<span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to "Profile", chefs_show_path(current_chef) %></li>
	            <li><%= link_to "Settings", edit_chef_registration_path %></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Log Out", destroy_chef_session_path, method: :delete %></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<% end %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>